changelog-seen = 2

[build]
host = ["wasm32-wasi"]
target = ["wasm32-wasi"]
extended = true
tools = ["cargo", "src"]

[rust]
lld = true
split-debuginfo = "off"

[llvm]
clang = true
ccache = "/usr/bin/ccache"

[target.wasm32-wasi]

cc = "#ROOT_PATH#/build/wasi-sdk/build/install/opt/wasi-sdk/bin/clang"

cxx = "#ROOT_PATH#/build/wasi-sdk/build/install/opt/wasi-sdk/bin/clang++"

ar = "#ROOT_PATH#/build/wasi-sdk/build/install/opt/wasi-sdk/bin/ar"

ranlib = "#ROOT_PATH#/build/wasi-sdk/build/install/opt/wasi-sdk/bin/ranlib"

linker = "#ROOT_PATH#/build/wasi-sdk/build/install/opt/wasi-sdk/bin/clang"

wasi-root = "#ROOT_PATH#/build/wasi-sdk/build/install/opt/wasi-sdk"
